# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 220, 211, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear = QtWidgets.QPushButton(self.layoutWidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.upload = QtWidgets.QPushButton(self.layoutWidget)
        self.upload.setObjectName("upload")
        self.horizontalLayout.addWidget(self.upload)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 50, 189, 122))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.custom_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.custom_name.setObjectName("custom_name")
        self.horizontalLayout_2.addWidget(self.custom_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.custom_id = QtWidgets.QLineEdit(self.layoutWidget1)
        self.custom_id.setObjectName("custom_id")
        self.horizontalLayout_4.addWidget(self.custom_id)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.select_school = QtWidgets.QComboBox(self.layoutWidget1)
        self.select_school.setObjectName("select_school")
        self.select_school.addItem("")
        self.select_school.addItem("")
        self.horizontalLayout_3.addWidget(self.select_school)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.upload_face = QtWidgets.QLabel(self.centralwidget)
        self.upload_face.setGeometry(QtCore.QRect(290, 50, 120, 120))
        self.upload_face.setAlignment(QtCore.Qt.AlignCenter)
        self.upload_face.setObjectName("upload_face")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear.setText(_translate("MainWindow", "清空"))
        self.upload.setText(_translate("MainWindow", "提交"))
        self.label.setText(_translate("MainWindow", "姓       名"))
        self.label_3.setText(_translate("MainWindow", "客户编码"))
        self.label_2.setText(_translate("MainWindow", "所属校区"))
        self.select_school.setItemText(0, _translate("MainWindow", "蓝港校区"))
        self.select_school.setItemText(1, _translate("MainWindow", "回龙观校区"))
        self.upload_face.setText(_translate("MainWindow", "上传图片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
