# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_page(object):
    def setupUi(self, login_page):
        login_page.setObjectName("login_page")
        login_page.resize(413, 262)
        login_page.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(login_page)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 261, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.custom_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.custom_name.setObjectName("custom_name")
        self.horizontalLayout_2.addWidget(self.custom_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.custom_pwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.custom_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.custom_pwd.setObjectName("custom_pwd")
        self.horizontalLayout_4.addWidget(self.custom_pwd)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setEnabled(True)
        self.login_btn.setGeometry(QtCore.QRect(70, 150, 261, 36))
        self.login_btn.setObjectName("login_btn")
        login_page.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login_page)
        self.statusbar.setObjectName("statusbar")
        login_page.setStatusBar(self.statusbar)

        self.retranslateUi(login_page)
        QtCore.QMetaObject.connectSlotsByName(login_page)

    def retranslateUi(self, login_page):
        _translate = QtCore.QCoreApplication.translate
        login_page.setWindowTitle(_translate("login_page", "登录"))
        self.label.setText(_translate("login_page", "姓       名"))
        self.label_3.setText(_translate("login_page", "密       码"))
        self.login_btn.setText(_translate("login_page", "登录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_page = QtWidgets.QMainWindow()
    ui = Ui_login_page()
    ui.setupUi(login_page)
    login_page.show()
    sys.exit(app.exec_())
